language: generic 
sudo: require
service:
  - docker

before_install:
  - docker build -t jamaldocker987/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jamaldocker987/react-test npm test

after_succes:
  - docker build -t jamaldocker987/multi-client ./client
  - docker build -t jamaldocker987/multi-nginx ./nginx
  - docker build -t jamaldocker987/multi-server ./server
  - docker build -t jamaldocker987/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push jamaldocker987/multi-client
  - docker push jamaldocker987/multi-nginx
  - docker push jamaldocker987/multi-server
  - docker push jamaldocker987/multi-worker
